name: "setup"
on:
  push:
    branches:
      - main
jobs:
  setup-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: sqlc-dev/setup-sqlc@main
      with:
        sqlc-version: '1.18.0'
    - run: sqlc version

  setup-windows:
    runs-on: windows-latest
    steps:
    - uses: sqlc-dev/setup-sqlc@main
      with:
        sqlc-version: '1.18.0'
    - run: sqlc version

  setup-mac:
    runs-on: macos-latest
    steps:
    - uses: sqlc-dev/setup-sqlc@main
      with:
        sqlc-version: '1.18.0'
    - run: sqlc version
